import { pgTable, text, integer, boolean, timestamp, unique, jsonb } from "drizzle-orm/pg-core";

export const eventParticipantsTable = pgTable(
  "event_participants",
  {
    id: integer("id").primaryKey().generatedAlwaysAsIdentity(),
    eventId: integer("event_id").notNull(),
    guildId: text("guild_id").notNull().default("1382035307607883816"),
    discordId: text("discord_id").notNull(),
    username: text("username").notNull(),
    classKey: text("class_key"),
    currentHp: integer("current_hp").notNull().default(100),
    maxHp: integer("max_hp").notNull().default(100),
    monsterLevel: integer("monster_level").notNull().default(1),
    monsterCurrentHp: integer("monster_current_hp").notNull().default(55),
    totalDamage: integer("total_damage").notNull().default(0),
    oboli: integer("oboli").notNull().default(0),
    xp: integer("xp").notNull().default(0),
    baseOboli: integer("base_oboli").notNull().default(0),
    baseXp: integer("base_xp").notNull().default(0),
    xpPerKill: integer("xp_per_kill").notNull().default(0),
    monsterRarity: text("monster_rarity").notNull().default("comun"),
    bossCharge: integer("boss_charge").notNull().default(0),
    abilityReadyAt: timestamp("ability_ready_at", { withTimezone: true }),
    empowerNext: boolean("empower_next").notNull().default(false),
    shieldNext: boolean("shield_next").notNull().default(false),
    shieldHp: integer("shield_hp").notNull().default(0),
    empowerLevel: integer("empower_level").notNull().default(0),
    shieldLevel: integer("shield_level").notNull().default(0),
    attackBonus: integer("attack_bonus").notNull().default(0),
    defenseBonus: integer("defense_bonus").notNull().default(0),
    dodgeBonus: integer("dodge_bonus").notNull().default(0),
    critBonus: integer("crit_bonus").notNull().default(0),
    shopAttackCount: integer("shop_attack_count").notNull().default(0),
    shopDefenseCount: integer("shop_defense_count").notNull().default(0),
    shopDodgeCount: integer("shop_dodge_count").notNull().default(0),
    shopCritCount: integer("shop_crit_count").notNull().default(0),
    shopHpCount: integer("shop_hp_count").notNull().default(0),
    isAlive: boolean("is_alive").notNull().default(true),
    fled: boolean("fled").notNull().default(false),
    itemsFarmed: jsonb("items_farmed").$type<Record<string, number>>().notNull().default({}),
    pendingLevelup: boolean("pending_levelup").notNull().default(false),
    joinedAt: timestamp("joined_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [unique().on(t.eventId, t.discordId)],
);

export type EventParticipant = typeof eventParticipantsTable.$inferSelect;
